Initialize suspenders app

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,29 +1,43 @@
-#!/usr/bin/env ruby
-require 'pathname'
+#!/bin/sh
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)
+# Set up Rails app. Run this script immediately after cloning the codebase.
+# https://github.com/thoughtbot/guides/tree/master/protocol
 
-Dir.chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file:
+# Exit if any subcommand fails
+set -e
 
-  puts "== Installing dependencies =="
-  system "gem install bundler --conservative"
-  system "bundle check || bundle install"
+# Set up Ruby dependencies via Bundler
+gem install bundler --conservative
+bundle check || bundle install
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?("config/database.yml")
-  #   system "cp config/database.yml.sample config/database.yml"
-  # end
+# Set up database and add any development seed data
+bin/rake dev:prime
 
-  puts "\n== Preparing database =="
-  system "bin/rake db:setup"
+# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
+mkdir -p .git/safe
 
-  puts "\n== Removing old logs and tempfiles =="
-  system "rm -f log/*"
-  system "rm -rf tmp/cache"
+# Only if this isn't CI
+# if [ -z "$CI" ]; then
+# fi
+          
+if heroku join --app lambda-staging &> /dev/null; then
+  git remote add staging git@heroku.com:lambda-staging.git || true
+  printf 'You are a collaborator on the "lambda-staging" Heroku app
+'
+else
+  printf 'Ask for access to the "lambda-staging" Heroku app
+'
+fi
 
-  puts "\n== Restarting application server =="
-  system "touch tmp/restart.txt"
-end
+          
+if heroku join --app lambda-production &> /dev/null; then
+  git remote add production git@heroku.com:lambda-production.git || true
+  printf 'You are a collaborator on the "lambda-production" Heroku app
+'
+else
+  printf 'Ask for access to the "lambda-production" Heroku app
+'
+fi
+
+
+          git config heroku.remote staging
